version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./postgres/socket:/var/run/postgresql"
 
  psql:
    image: postgres:11.9
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=database
    network_mode: service:app
    volumes:
      - "./postgres/socket:/var/run/postgresql"